# Generated by Django 5.0.1 on 2024-02-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service_watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingservices',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servicesprovided',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
